### ISSUE TITLE
performance with flashlight

### ISSUE THREAD

**Issue by ak1dd** [caligari87/darkdoomz#12]
I have a fairly new rig but when I turn on any of the flashlights other than Simple the framerate drops to unplayable.

**Comment by caligari87** [comment]
Flashlight performance isn't something I can do much to improve at this point. The bottleneck is engine-side and highly dependent on the following factors:

* Intensity (brightness) of the light.
* Number of moving lights (simple uses 1, fancy uses 2).
* Number of lindefs in the light's *radius* (not just cone).
* Your system's single-thread CPU performance.

So if you're playing a map with more detail than a stock Doom map, it's very likely you'll get performance issues with the brighter lights, especially when set to Fancy. That's why the quality and brightness settings are there; to tweak the appearance if it's causing issues.

The good news is, the next stable version of GZDoom should have improved dynamic light linking, which some people using devbuilds have reported increasing performance by a large amount.
